services:
  api:
    build:
      context: ./backend # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Mount the backend code directory for hot-reloading
      - ./backend:/app
      # Ensure the database file is available inside the container
      # This overrides the DB file potentially copied during build
      - ./backend/database.sqlite:/app/database.sqlite
    environment:
      # Optional: Define environment variables if needed by the app
      # EXAMPLE_VAR: example_value
      PYTHONUNBUFFERED: 1 # Already set in Dockerfile, but good practice here too
    # The command in the Dockerfile is already set to run with --reload,
    # but specifying it here ensures it overrides any base image CMD if needed.
    # It also makes the development setup explicit.
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5173:5173" # Default Vite dev port
    volumes:
      # Mount the entire frontend directory for hot-reloading
      - ./frontend:/app
      # Avoid mounting node_modules from the host, let the container manage it
      - /app/node_modules
    environment:
      NODE_ENV: development
    # Run the development server, ensuring it's accessible externally
    # The specific script name ('dev') comes from standard Vite setups in package.json
    command: npm run dev -- --host 0.0.0.0
